In [ ]:
import pandas as pd
url = 'https://raw.githubusercontent.com/saputrr/saputrr.github.io/refs/heads/main/API_NY.GDP.PCAP.PP.CD_DS2_en_csv_v2_9326.csv'
df = pd.read_csv(url, header=4)

df

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Aruba,ABW,"GDP per capita, PPP (current international $)",NY.GDP.PCAP.PP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,36763.209000,37231.918500,37444.441090,38697.949510,40379.293720,40124.758000,30437.202520,38226.146160,45236.021210,NaN
1,Africa Eastern and Southern,AFE,"GDP per capita, PPP (current international $)",NY.GDP.PCAP.PP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,3473.843253,3502.296662,3595.841041,3640.628582,3695.386884,3783.518751,3666.871961,3967.400629,4294.025281,4459.764134
2,Afghanistan,AFG,"GDP per capita, PPP (current international $)",NY.GDP.PCAP.PP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2229.679539,2289.371986,2217.296786,2338.778697,2436.006320,2589.410396,2568.341909,2138.870247,2092.879952,NaN
3,Africa Western and Central,AFW,"GDP per capita, PPP (current international $)",NY.GDP.PCAP.PP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,4180.427724,4130.736274,4072.792261,4139.387604,4272.387852,4525.091244,4503.396648,4756.308419,5156.120103,5389.580896
4,Angola,AGO,"GDP per capita, PPP (current international $)",NY.GDP.PCAP.PP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,7999.826851,7127.339573,6850.384625,6998.796187,7353.349988,7533.511854,6455.119982,7414.278958,7928.641498,8040.543601
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,"GDP per capita, PPP (current international $)",NY.GDP.PCAP.PP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,8200.551108,8715.299803,9157.102974,9381.023878,10018.744280,10861.132100,10532.611370,12362.704810,13939.456500,15029.349100
262,"Yemen, Rep.",YEM,"GDP per capita, PPP (current international $)",NY.GDP.PCAP.PP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263,South Africa,ZAF,"GDP per capita, PPP (current international $)",NY.GDP.PCAP.PP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,13570.149710,13600.616800,13719.943190,13979.523870,13643.774140,13706.713820,13062.672770,14172.544250,15330.769270,15847.427560
264,Zambia,ZMB,"GDP per capita, PPP (current international $)",NY.GDP.PCAP.PP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,3475.759629,3368.460312,3342.331991,3419.717835,3468.844121,3385.786570,3179.265411,3526.507418,3864.894367,4125.625556
265,Zimbabwe,ZWE,"GDP per capita, PPP (current international $)",NY.GDP.PCAP.PP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2618.240859,2692.290700,2825.357165,2435.794358,2611.326409,2711.529334,2784.872395,3276.267753,3660.835501,3899.899233

In [ ]:
df = df.rename(columns={
    'Country Name': 'country',
    'Country Code':	'code',
    'Indicator Name':	'series',
    'Indicator Code': 'series_code',
})
df.head()

,country,code,series,series_code,1960,1961,1962,1963,1964,1965,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Aruba,ABW,"GDP per capita, PPP (current international $)",NY.GDP.PCAP.PP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,36763.209000,37231.918500,37444.441090,38697.949510,40379.293720,40124.758000,30437.202520,38226.146160,45236.021210,NaN
1,Africa Eastern and Southern,AFE,"GDP per capita, PPP (current international $)",NY.GDP.PCAP.PP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,3473.843253,3502.296662,3595.841041,3640.628582,3695.386884,3783.518751,3666.871961,3967.400629,4294.025281,4459.764134
2,Afghanistan,AFG,"GDP per capita, PPP (current international $)",NY.GDP.PCAP.PP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2229.679539,2289.371986,2217.296786,2338.778697,2436.006320,2589.410396,2568.341909,2138.870247,2092.879952,NaN
3,Africa Western and Central,AFW,"GDP per capita, PPP (current international $)",NY.GDP.PCAP.PP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,4180.427724,4130.736274,4072.792261,4139.387604,4272.387852,4525.091244,4503.396648,4756.308419,5156.120103,5389.580896
4,Angola,AGO,"GDP per capita, PPP (current international $)",NY.GDP.PCAP.PP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,7999.826851,7127.339573,6850.384625,6998.796187,7353.349988,7533.511854,6455.119982,7414.278958,7928.641498,8040.543601

In [ ]:
df.melt(id_vars=['country', 'code', 'series', 'series_code'])

,country,code,series,series_code,variable,value
0,Aruba,ABW,"GDP per capita, PPP (current international $)",NY.GDP.PCAP.PP.CD,1960,NaN
1,Africa Eastern and Southern,AFE,"GDP per capita, PPP (current international $)",NY.GDP.PCAP.PP.CD,1960,NaN
2,Afghanistan,AFG,"GDP per capita, PPP (current international $)",NY.GDP.PCAP.PP.CD,1960,NaN
3,Africa Western and Central,AFW,"GDP per capita, PPP (current international $)",NY.GDP.PCAP.PP.CD,1960,NaN
4,Angola,AGO,"GDP per capita, PPP (current international $)",NY.GDP.PCAP.PP.CD,1960,NaN
...,...,...,...,...,...,...
17019,Kosovo,XKX,"GDP per capita, PPP (current international $)",NY.GDP.PCAP.PP.CD,2023,15029.349100
17020,"Yemen, Rep.",YEM,"GDP per capita, PPP (current international $)",NY.GDP.PCAP.PP.CD,2023,NaN
17021,South Africa,ZAF,"GDP per capita, PPP (current international $)",NY.GDP.PCAP.PP.CD,2023,15847.427560
17022,Zambia,ZMB,"GDP per capita, PPP (current international $)",NY.GDP.PCAP.PP.CD,2023,4125.625556
17023,Zimbabwe,ZWE,"GDP per capita, PPP (current international $)",NY.GDP.PCAP.PP.CD,2023,3899.899233

In [ ]:
df = df.drop(columns=['series', 'series_code'])
df

,country,code,1960,1961,1962,1963,1964,1965,1966,1967,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,36763.209000,37231.918500,37444.441090,38697.949510,40379.293720,40124.758000,30437.202520,38226.146160,45236.021210,NaN
1,Africa Eastern and Southern,AFE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3473.843253,3502.296662,3595.841041,3640.628582,3695.386884,3783.518751,3666.871961,3967.400629,4294.025281,4459.764134
2,Afghanistan,AFG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2229.679539,2289.371986,2217.296786,2338.778697,2436.006320,2589.410396,2568.341909,2138.870247,2092.879952,NaN
3,Africa Western and Central,AFW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4180.427724,4130.736274,4072.792261,4139.387604,4272.387852,4525.091244,4503.396648,4756.308419,5156.120103,5389.580896
4,Angola,AGO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7999.826851,7127.339573,6850.384625,6998.796187,7353.349988,7533.511854,6455.119982,7414.278958,7928.641498,8040.543601
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8200.551108,8715.299803,9157.102974,9381.023878,10018.744280,10861.132100,10532.611370,12362.704810,13939.456500,15029.349100
262,"Yemen, Rep.",YEM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263,South Africa,ZAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13570.149710,13600.616800,13719.943190,13979.523870,13643.774140,13706.713820,13062.672770,14172.544250,15330.769270,15847.427560
264,Zambia,ZMB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3475.759629,3368.460312,3342.331991,3419.717835,3468.844121,3385.786570,3179.265411,3526.507418,3864.894367,4125.625556
265,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2618.240859,2692.290700,2825.357165,2435.794358,2611.326409,2711.529334,2784.872395,3276.267753,3660.835501,3899.899233

In [ ]:
df1 = df.melt(id_vars=['country', 'code'], var_name='year')

df1

                           country code  year         value
0                            Aruba  ABW  1960           NaN
1      Africa Eastern and Southern  AFE  1960           NaN
2                      Afghanistan  AFG  1960           NaN
3       Africa Western and Central  AFW  1960           NaN
4                           Angola  AGO  1960           NaN
...                            ...  ...   ...           ...
17019                       Kosovo  XKX  2023  15029.349100
17020                  Yemen, Rep.  YEM  2023           NaN
17021                 South Africa  ZAF  2023  15847.427560
17022                       Zambia  ZMB  2023   4125.625556
17023                     Zimbabwe  ZWE  2023   3899.899233

[17024 rows x 4 columns]

In [ ]:
df1 = df1.dropna()
df1

                           country code  year         value
7980                         Aruba  ABW  1990  20754.231460
7981   Africa Eastern and Southern  AFE  1990   1816.035866
7983    Africa Western and Central  AFW  1990   1741.687520
7984                        Angola  AGO  1990   3283.471906
7985                       Albania  ALB  1990   2549.256454
...                            ...  ...   ...           ...
17018                        Samoa  WSM  2023   6680.611386
17019                       Kosovo  XKX  2023  15029.349100
17021                 South Africa  ZAF  2023  15847.427560
17022                       Zambia  ZMB  2023   4125.625556
17023                     Zimbabwe  ZWE  2023   3899.899233

[8252 rows x 4 columns]

In [ ]:
df1 = df1[df1['country'] == 'Indonesia'].copy()
df1.head()

        country code  year        value
8086  Indonesia  IDN  1990  3070.264554
8352  Indonesia  IDN  1991  3330.632075
8618  Indonesia  IDN  1992  3566.357955
8884  Indonesia  IDN  1993  3823.607598
9150  Indonesia  IDN  1994  4130.948987

In [ ]:
df1.to_csv('GDPpercap.csv', index=False)

In [ ]:
import altair as alt

chart = alt.Chart(df1).mark_line().encode(
          alt.X('year'),
          alt.Y('value'),
          )

In [ ]:
chart_json = chart.to_json()
print(chart_json)

{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.17.0.json",
  "config": {
    "view": {
      "continuousHeight": 300,
      "continuousWidth": 400
    }
  },
  "data": {
    "name": "data-27bd0b3d1f599c7a0efcb0001a60cb7a"
  },
  "datasets": {
    "data-27bd0b3d1f599c7a0efcb0001a60cb7a": [
      {
        "code": "IDN",
        "country": "Indonesia",
        "value": 3070.264554,
        "year": "1990"
      },
      {
        "code": "IDN",
        "country": "Indonesia",
        "value": 3330.632075,
        "year": "1991"
      },
      {
        "code": "IDN",
        "country": "Indonesia",
        "value": 3566.357955,
        "year": "1992"
      },
      {
        "code": "IDN",
        "country": "Indonesia",
        "value": 3823.607598,
        "year": "1993"
      },
      {
        "code": "IDN",
        "country": "Indonesia",
        "value": 4130.948987,
        "year": "1994"
      },
      {
        "code": "IDN",
        "country": "Indonesia",
        "value": 4490.264746,
        "year": "1995"
      },
      {
        "code": "IDN",
        "country": "Indonesia",
        "value": 4850.790798,
        "year": "1996"
      },
      {
        "code": "IDN",
        "country": "Indonesia",
        "value": 5084.191936,
        "year": "1997"
      },
      {
        "code": "IDN",
        "country": "Indonesia",
        "value": 4397.090203,
        "year": "1998"
      },
      {
        "code": "IDN",
        "country": "Indonesia",
        "value": 4427.674474,
        "year": "1999"
      },
      {
        "code": "IDN",
        "country": "Indonesia",
        "value": 4682.496616,
        "year": "2000"
      },
      {
        "code": "IDN",
        "country": "Indonesia",
        "value": 4892.895213,
        "year": "2001"
      },
      {
        "code": "IDN",
        "country": "Indonesia",
        "value": 5121.673837,
        "year": "2002"
      },
      {
        "code": "IDN",
        "country": "Indonesia",
        "value": 5399.724306,
        "year": "2003"
      },
      {
        "code": "IDN",
        "country": "Indonesia",
        "value": 5750.204743,
        "year": "2004"
      },
      {
        "code": "IDN",
        "country": "Indonesia",
        "value": 6189.56886,
        "year": "2005"
      },
      {
        "code": "IDN",
        "country": "Indonesia",
        "value": 6644.53394,
        "year": "2006"
      },
      {
        "code": "IDN",
        "country": "Indonesia",
        "value": 7162.984355,
        "year": "2007"
      },
      {
        "code": "IDN",
        "country": "Indonesia",
        "value": 7639.919098,
        "year": "2008"
      },
      {
        "code": "IDN",
        "country": "Indonesia",
        "value": 7941.243696,
        "year": "2009"
      },
      {
        "code": "IDN",
        "country": "Indonesia",
        "value": 8431.821765,
        "year": "2010"
      },
      {
        "code": "IDN",
        "country": "Indonesia",
        "value": 9022.72138,
        "year": "2011"
      },
      {
        "code": "IDN",
        "country": "Indonesia",
        "value": 9624.588232,
        "year": "2012"
      },
      {
        "code": "IDN",
        "country": "Indonesia",
        "value": 9966.382935,
        "year": "2013"
      },
      {
        "code": "IDN",
        "country": "Indonesia",
        "value": 10168.67606,
        "year": "2014"
      },
      {
        "code": "IDN",
        "country": "Indonesia",
        "value": 10132.31608,
        "year": "2015"
      },
      {
        "code": "IDN",
        "country": "Indonesia",
        "value": 10371.44233,
        "year": "2016"
      },
      {
        "code": "IDN",
        "country": "Indonesia",
        "value": 10802.7126,
        "year": "2017"
      },
      {
        "code": "IDN",
        "country": "Indonesia",
        "value": 11494.94485,
        "year": "2018"
      },
      {
        "code": "IDN",
        "country": "Indonesia",
        "value": 12115.70207,
        "year": "2019"
      },
      {
        "code": "IDN",
        "country": "Indonesia",
        "value": 11856.94333,
        "year": "2020"
      },
      {
        "code": "IDN",
        "country": "Indonesia",
        "value": 12897.10314,
        "year": "2021"
      },
      {
        "code": "IDN",
        "country": "Indonesia",
        "value": 14445.64316,
        "year": "2022"
      },
      {
        "code": "IDN",
        "country": "Indonesia",
        "value": 15612.79912,
        "year": "2023"
      }
    ]
  },
  "encoding": {
    "x": {
      "field": "year",
      "type": "nominal"
    },
    "y": {
      "field": "value",
      "type": "quantitative"
    }
  },
  "mark": "line"
}

/usr/local/lib/python3.10/dist-packages/altair/utils/core.py:384: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/usr/local/lib/python3.10/dist-packages/altair/utils/core.py:384: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/usr/local/lib/python3.10/dist-packages/altair/utils/core.py:384: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)