<a href="https://colab.research.google.com/github/saputrr/saputrr.github.io/blob/main/Maps.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [5]:
url = 'https://raw.githubusercontent.com/saputrr/saputrr.github.io/refs/heads/main/IDN_regional_gdp.csv'
df = pd.read_csv(url, skiprows=1)
df.rename(columns={"Unnamed: 0": "province"}, inplace=True)
df = df.iloc[:-2]
df

,province,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Aceh,-,3.28,3.85,2.61,1.55,-0.73,3.29,4.18,4.61,4.14,-0.37,2.81,4.21,4.23
1,Sumatera Utara,-,6.66,6.45,6.07,5.23,5.1,5.18,5.12,5.18,5.22,-1.07,2.61,4.73,5.01
2,Sumatera Barat,-,6.34,6.31,6.08,5.88,5.53,5.27,5.3,5.14,5.01,-1.61,3.29,4.36,4.62
3,Riau,-,5.57,3.76,2.48,2.71,0.22,2.18,2.66,2.35,2.81,-1.13,3.36,4.55,4.21
4,Jambi,-,7.86,7.03,6.84,7.36,4.21,4.37,4.6,4.69,4.35,-0.51,3.7,5.12,4.66
5,Sumatera Selatan,-,6.36,6.83,5.31,4.79,4.42,5.04,5.51,6.01,5.69,-0.11,3.58,5.23,5.08
6,Bengkulu,-,6.85,6.83,6.07,5.48,5.13,5.28,4.98,4.97,4.94,-0.02,3.27,4.31,4.26
7,Lampung,-,6.56,6.44,5.77,5.08,5.13,5.14,5.16,5.23,5.26,-1.66,2.77,4.28,4.55
8,Kep. Bangka Belitung,-,6.9,5.5,5.2,4.67,4.08,4.1,4.47,4.45,3.32,-2.29,5.05,4.4,4.38
9,Kep. Riau,-,6.96,7.63,7.21,6.6,6.02,4.98,1.98,4.47,4.83,-3.8,3.43,5.09,5.20
10,DKI Jakarta,-,6.73,6.53,6.07,5.91,5.91,5.87,6.2,6.11,5.82,-2.39,3.55,5.25,4.96
11,Jawa Barat,-,6.5,6.5,6.33,5.09,5.05,5.66,5.33,5.65,5.02,-2.52,3.74,5.45,5.00
12,Jawa Tengah,-,5.3,5.34,5.11,5.27,5.47,5.25,5.26,5.3,5.36,-2.65,3.33,5.31,4.98
13,DI Yogyakarta,-,5.21,5.37,5.47,5.17,4.95,5.05,5.26,6.2,6.59,-2.67,5.58,5.15,5.07
14,Jawa Timur,-,6.44,6.64,6.08,5.86,5.44,5.57,5.46,5.47,5.53,-2.33,3.56,5.34,4.95
15,Banten,-,7.03,6.83,6.67,5.51,5.45,5.28,5.75,5.77,5.26,-3.39,4.49,5.03,4.81
16,Bali,-,6.66,6.96,6.69,6.73,6.03,6.33,5.56,6.31,5.6,-9.34,-2.46,4.84,5.71
17,Nusa Tenggara Barat,-,-3.91,-1.54,5.16,5.17,21.76,5.81,0.09,-4.5,3.9,-0.62,2.3,6.95,1.80
18,Nusa Tenggara Timur,-,5.67,5.46,5.41,5.05,4.92,5.12,5.11,5.11,5.25,-0.84,2.52,3.05,3.52
19,Kalimantan Barat,-,5.5,5.91,6.05,5.03,4.88,5.2,5.17,5.07,5.09,-1.82,4.8,5.07,4.46
20,Kalimantan Tengah,-,7.01,6.87,7.37,6.21,7.01,6.35,6.73,5.61,6.12,-1.41,3.59,6.45,4.14
21,Kalimantan Selatan,-,6.97,5.97,5.33,4.84,3.82,4.4,5.28,5.08,4.09,-1.82,3.48,5.11,4.84
22,Kalimantan Timur,-,6.47,5.48,2.76,1.71,-1.2,-0.38,3.13,2.64,4.7,-2.9,2.55,4.48,6.22
23,Kalimantan Utara,-,-,-,-,8.18,3.4,3.55,6.8,5.36,6.89,-1.09,3.99,5.32,4.94
24,Sulawesi Utara,-,6.17,6.86,6.38,6.31,6.12,6.16,6.31,6,5.65,-0.99,4.16,5.42,5.48
25,Sulawesi Tengah,-,9.82,9.53,9.59,5.07,15.5,9.94,7.1,20.6,8.83,4.86,11.68,15.22,11.91
26,Sulawesi Selatan,-,8.13,8.87,7.62,7.54,7.19,7.42,7.21,7.04,6.91,-0.71,4.64,5.1,4.51
27,Sulawesi Tenggara,-,10.63,11.65,7.5,6.26,6.88,6.51,6.76,6.4,6.5,-0.65,4.1,5.53,5.35
28,Gorontalo,-,7.71,7.91,7.67,7.27,6.22,6.52,6.73,6.49,6.4,-0.02,2.4,4.04,4.50
29,Sulawesi Barat,-,10.73,9.25,6.93,8.86,7.31,6.01,6.39,6.26,5.56,-2.34,2.57,2.31,5.25
30,Maluku,-,6.34,7.16,5.24,6.64,5.48,5.73,5.82,5.91,5.41,-0.91,3.63,5.31,5.21
31,Maluku Utara,-,6.8,6.98,6.36,5.49,6.1,5.77,7.67,7.86,6.25,5.39,16.79,22.94,20.49
32,Papua Barat,-,3.64,3.63,7.36,5.38,4.15,4.52,4.02,6.25,2.66,-0.76,-0.51,2.01,5.18
33,Papua Barat Daya,-,-,-,-,-,-,-,-,-,-,-,-,-,1.82
34,Papua,-,-4.28,1.72,8.55,3.65,7.35,9.14,4.64,7.32,-15.74,2.39,15.16,8.97,4.20
35,Papua Selatan,-,-,-,-,-,-,-,-,-,-,-,-,-,4.27
36,Papua Tengah,-,-,-,-,-,-,-,-,-,-,-,-,-,5.95
37,Papua Pegunungan,-,-,-,-,-,-,-,-,-,-,-,-,-,4.78
38,Indonesia,-,6.16,6.16,5.74,5.21,-,5.03,5.07,5.17,5.02,-2.07,3.7,5.31,5.05

In [9]:
rgdp_df = df.melt(id_vars=['province'], var_name='year', value_name='rgdp') # Moving our data from wide to long format
rgdp_df.columns = ['province', 'year', 'rgdp'] # Renaming the columns

rgdp_df

             province  year  rgdp
0                Aceh  2010     -
1      Sumatera Utara  2010     -
2      Sumatera Barat  2010     -
3                Riau  2010     -
4               Jambi  2010     -
..                ...   ...   ...
541             Papua  2023   4.2
542     Papua Selatan  2023  4.27
543      Papua Tengah  2023  5.95
544  Papua Pegunungan  2023  4.78
545         Indonesia  2023  5.05

[546 rows x 3 columns]

In [10]:
rgdp_df.to_csv('IDN_rgdp.csv', index=False)